apiVersion: v1
kind: ConfigMap
metadata:
  name: pm-lab-config
  namespace: prometheus-lab
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
        - targets: ['localhost:9090']
