
#  ██████ ██      ██    ██ ███████ ████████ ███████ ██████  ██ ██████
# ██      ██      ██    ██ ██         ██    ██      ██   ██ ██ ██   ██
# ██      ██      ██    ██ ███████    ██    █████   ██████  ██ ██████
# ██      ██      ██    ██      ██    ██    ██      ██   ██ ██ ██
#  ██████ ███████  ██████  ███████    ██    ███████ ██   ██ ██ ██

apiVersion: v1
kind: Service
metadata:
  name: pm-lab-clusterip
  namespace: prometheus-lab
  labels:
    app: pm-lab-clusterip
spec:
  type: ClusterIP
  ports:
     -  port: 9090
        protocol: TCP
        targetPort: 9090
  selector:
    app: pm-lab


# ███    ██  ██████  ██████  ███████ ██████   ██████  ██████  ████████
# ████   ██ ██    ██ ██   ██ ██      ██   ██ ██    ██ ██   ██    ██
# ██ ██  ██ ██    ██ ██   ██ █████   ██████  ██    ██ ██████     ██
# ██  ██ ██ ██    ██ ██   ██ ██      ██      ██    ██ ██   ██    ██
# ██   ████  ██████  ██████  ███████ ██       ██████  ██   ██    ██

apiVersion: v1
kind: Service
metadata:
  name: pm-lab-nodeport
  namespace: prometheus-lab
  labels:
    app: pm-lab-nodeport
spec:
  type: NodePort
  ports:
     -  port: 9090
        protocol: TCP
        targetPort: 9090
        nodePort: 30090
  selector:
    app: pm-lab


# ██       ██████   █████  ██████  ██████   █████  ██       █████  ███    ██  ██████ ███████ ██████
# ██      ██    ██ ██   ██ ██   ██ ██   ██ ██   ██ ██      ██   ██ ████   ██ ██      ██      ██   ██
# ██      ██    ██ ███████ ██   ██ ██████  ███████ ██      ███████ ██ ██  ██ ██      █████   ██████
# ██      ██    ██ ██   ██ ██   ██ ██   ██ ██   ██ ██      ██   ██ ██  ██ ██ ██      ██      ██   ██
# ███████  ██████  ██   ██ ██████  ██████  ██   ██ ███████ ██   ██ ██   ████  ██████ ███████ ██   ██

apiVersion: v1
kind: Service
metadata:
  name: pm-lab-loadbalancer
  namespace: prometheus-lab
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  ports:
     -  port: 80
        protocol: TCP
        targetPort: 9090
  selector:
    app: pm-lab
